name: Tests

on:
  - pull_request
env:
  CI: "true"

jobs:
  run:
    name: On Node 18
    runs-on: ubuntu-20.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: |
            package-lock.json
            functions/package-lock.json

      - name: Install functions npm dependencies
        working-directory: ./functions
        run: npm ci

      - name: Run functions tests
        working-directory: ./functions
        run: npm test

      - name: Install npm dependencies
        working-directory: ./
        run: npm ci

      - name: Run tests
        working-directory: ./
        run: npm test
